require "base64"
default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    raw_p8 = Base64.decode64(ENV["ASC_PRIVATE_KEY"])
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: raw_p8
    )

    build_app(
      project: "Lobah.xcodeproj",
      scheme: "Lobah",
      configuration: "Release",
      output_directory: "./output",
      output_name: "Lobah.ipa",
      xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
