lane :beta do
  api_key = app_store_connect_api_key(
    key_id: ENV["ASC_KEY_ID"],
    issuer_id: ENV["ASC_ISSUER_ID"],
    key_filepath: "./auth_key.p8",
    duration: 1200
  )

  match(app_store: true, api_key: api_key)

  build_app(
    project: "Lobah.xcodeproj",
    scheme: "Lobah",
    configuration: "Release",
    output_directory: "./output",
    output_name: "Lobah.ipa"
  )

  upload_to_testflight(
    api_key: api_key,
    skip_waiting_for_build_processing: true
  )
end
