default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_PRIVATE_KEY"],
      is_key_content_base64: false
    )

    build_app(
      project: "Lobah.xcodeproj",
      scheme: "Lobah", # ⚠️ 务必确认本地Xcode里Scheme名称就是 Lobah
      configuration: "Release",
      output_directory: "./output",
      output_name: "Lobah.ipa"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
